name: Terraform

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Elige el entorno Terraform'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - stage
          - prod

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Terraform CLI
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Terraform Init
        working-directory: terraform/envs/${{ github.event.inputs.environment }}
        run: terraform init \
          -backend-config=backend.tf

      - name: Terraform Plan
        working-directory: terraform/envs/${{ github.event.inputs.environment }}
        run: terraform plan -out plan.tfplan

      - name: Terraform Apply
        if: ${{ github.event_name == 'workflow_dispatch' }}
        working-directory: terraform/envs/${{ github.event.inputs.environment }}
        run: |
          read -p "¿Aplicar plan en ${{ github.event.inputs.environment }}? (y/n): " confirm
          if [ "$confirm" = "y" ]; then
            terraform apply -auto-approve plan.tfplan
          else
            echo "Apply cancelado."
          fi