trigger: none
pr: none

parameters:
  - name: environment
    displayName: 'Selecciona un entorno'
    type: string
    default: dev
    values:
      - dev
      - stage
      - prod

variables:
  - name: azureSubscription
    value: 'MiServiceConnectionAzure'
    
stages:
  - stage: TerraformDestroy
    displayName: 'Terraform en ${{ parameters.environment }}'
    jobs:
      - job: apply
        displayName: 'Destroy ${{ parameters.environment }}'
        pool:
          name: 'Default'
        steps:
          - task: TerraformInstaller@1
            inputs:
              terraformVersion: 'latest'
          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'init'
              workingDirectory: 'terraform/envs/${{ parameters.environment }}'
              backendServiceArm: 'ecommerce-terraform-sc'
              backendAzureRmResourceGroupName: 'tfstate-rg'
              backendAzureRmStorageAccountName: 'tfstateaccicesi'
              backendAzureRmContainerName: 'tfstate'
              backendAzureRmKey: '${{ parameters.environment }}.terraform.tfstate'
          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'destroy'
              workingDirectory: 'terraform/envs/${{ parameters.environment }}'
              environmentServiceNameAzureRM: 'ecommerce-terraform-sc'